server:
  port: 8031

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: turbine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

turbine:
  stream:
    port: 8030

management:
  server:
    port: 8030
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.web: debug
  path: logs/
  file:
    max-size: 1GB