server:
  port: 8022

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #spring boot admin设置权限，故需要通过账号密码获取注册信息
  instance:
    metadata-map:
      user.name: admin
      user.password: 123456

spring:
  application:
    name: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
    ##password: ${REDIS_PASSWORD:}
  #spring boot admin的登陆账号和密码配置
  security:
    user:
      name: admin
      password: 123456
  #通过rabbit MQ将日志发给zipkin
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
#日志相关配置
logging:
  level:
    org.springframework.security: DEBUG
  path: logs/
  file:
    max-size: 1GB